name: TesteAmbientes
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    # Especifica que este job roda no ambiente dev com uma url setada para a aplicação
    environment: 
      name: dev
      url: 'thiagosilvadev.com'
    # cria uma hierarquia ao especificar do job do qual este depende, nesse caso, build precisa rodar antes de deploy-dev
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Realizando o deploy-dev
        
  deploy-hom:
    runs-on: ubuntu-latest
    # Especifica que este job roda no ambiente dev com uma url setada para a aplicação
    environment: 
      name: hom
      url: 'thiagosilvadev.com'
    # cria uma hierarquia ao especificar do job do qual este depende, nesse caso, deploy-dev precisa rodar antes de deploy-hom
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v2
      - name: Realizando o deploy-hom
      
  deploy-prod:
    runs-on: ubuntu-latest
    # Especifica que este job roda no ambiente dev com uma url setada para a aplicação
    environment: 
      name: prod
      url: 'thiagosilvadev.com'
    # cria uma hierarquia ao especificar do job do qual este depende, nesse caso, deploy-hom precisa rodar antes de deploy-prod
    needs: deploy-hom
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Realizando o deploy-prod


