name: Meu-Primeiro-Fluxo

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configurando o node js
        uses: actions/setup-node@v2.1.5

      - uses: actions/checkout@v1

      - name: Rodando um script de 1 linha
        run: echo Olá Mundo CI/CD

      - name: Rodando script de várias linhas
        run: |
          echo Esta é a primeira saída desta ação
          echo Esta é outra saída desta ação